version: "3"

networks:
  my-net:
    external: true

services:
  jenkins-blueocean:
    build:
      context: ./
      args:
          HOST_GID: ${HOST_GID}
    container_name: jenkins-blueocean
    image: my-jenkins-blueocean:1.2
    restart: unless-stopped
    networks:
      - my-net
    ports:
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'jenkins-data:/var/jenkins_home'
